// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXzT5M0Osguu1ssIIFgDnLdITr_IFKhvs',
    appId: '1:3253954281:web:a0974c0b4dcf7bb2ad3278',
    messagingSenderId: '3253954281',
    projectId: 'location-tracker-2dae0',
    authDomain: 'location-tracker-2dae0.firebaseapp.com',
    storageBucket: 'location-tracker-2dae0.firebasestorage.app',
    measurementId: 'G-BB4XNEBK6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8pqCzVkoWaqWJJuL2CgaskbX6-nWpjQ8',
    appId: '1:3253954281:android:c72f244de2c27bd8ad3278',
    messagingSenderId: '3253954281',
    projectId: 'location-tracker-2dae0',
    storageBucket: 'location-tracker-2dae0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdUv1JDnCDmfMeDP_VhZGSzSkySftUx84',
    appId: '1:3253954281:ios:206650a0d34793e6ad3278',
    messagingSenderId: '3253954281',
    projectId: 'location-tracker-2dae0',
    storageBucket: 'location-tracker-2dae0.firebasestorage.app',
    iosBundleId: 'com.example.locationTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdUv1JDnCDmfMeDP_VhZGSzSkySftUx84',
    appId: '1:3253954281:ios:206650a0d34793e6ad3278',
    messagingSenderId: '3253954281',
    projectId: 'location-tracker-2dae0',
    storageBucket: 'location-tracker-2dae0.firebasestorage.app',
    iosBundleId: 'com.example.locationTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXzT5M0Osguu1ssIIFgDnLdITr_IFKhvs',
    appId: '1:3253954281:web:396bcbc7244e2b97ad3278',
    messagingSenderId: '3253954281',
    projectId: 'location-tracker-2dae0',
    authDomain: 'location-tracker-2dae0.firebaseapp.com',
    storageBucket: 'location-tracker-2dae0.firebasestorage.app',
    measurementId: 'G-SDYX2VF42Z',
  );
}
